version: '2'
services:
    ##
    # Autodiscovery : Consul
    ##
    autodiscovery:
        build: ./autodiscovery/
        mem_limit: 128m
        expose:
            - 53
            - 8300
            - 8301
            - 8302
            - 8400
            - 8500
        ports:
            - 8500:8500
        dns:
            - 127.0.0.1

    ##
    # Battle Microservice
    ##
    php7_fpm:
        build: ./microservices/battle/php-fpm/
        volumes_from:
            - source_base
        expose:
            - 9000
        environment:
            - BACKEND=nginx-image
            - CONSUL=autodiscovery

    nginx_image:
        build: ./microservices/battle/nginx/
        volumes_from:
            - source_base
        links:
            - autodiscovery
            - php7_fpm
        environment:
            - BACKEND=php7-fpm
            - CONSUL=autodiscovery
        ports:
            - 8081:80
            - 9091:9090
    ##
    # Source containers
    ##
    source_base:
        image: nginx:stable
        volumes:
            - ../source:/var/www/html
        command: "true"